### ISSUE TITLE
Recorder no longer working

### ISSUE THREAD

**Issue by redcomando1** [agnosto/fansly-recorder#5]
The python code seems to no longer work, the code would run, however no recording would be made and would appear as if no stream was happening even while live.

ie [username] is offline, checking again in 300s

internet working...

**Comment by agnosto** [comment]
I just pushed an update that makes it more closely follow a slightly altered script I had, that to my knowledge still works.  I am in a new dev environment and haven't ran the script on here at all yet, as well as I lost access to my testing fansly account, so I don't even know if anyone is live for me to test right now.

I do believe one of the changes revolved around checking if you actually had access to see the stream (followed / subbed / bought ticket / etc) and to stop it from crashing if you didn't have access and they were live (at least what I remember would happen), which may be where the issue of it saying they're offline even if on the homepage it shows them being live with the notification/preview thing, may come from.

If it continues to not work, let me know, I'll try to help debug.

**Comment by redcomando1** [comment]
Will do thank you

**Comment by redcomando1** [comment]
Just tried it again and still having  [username] is offline, checking again in 300s

**Comment by agnosto** [comment]
And when you go to the live for the user you can see it?

**Comment by redcomando1** [comment]
Yes user can be live but recorder will not start getting data

**Comment by agnosto** [comment]
I just pushed another change, think it might help with properly getting the data to start recording

**Comment by redcomando1** [comment]
been trying to find reason why it still wasn't working....
Doing an apt-get upgrade to check if updating the packages will help, 
don't know might have to do a clean install or something?

**Comment by redcomando1** [comment]
.... 
unknown what happened? However, after doing an apt-get update and running a pip install for the requirement.txt twice after about an hour recorder started recording properly.....

Was about to start testing in a vm for need for a clean install, however if this continues to work I dont think I'll need to.....

My best guess is after restarting the tmux session and waiting for 30 minutes it started working?

Guess I'll close the recorder for now and open again if same problem occurs.
